name: EraCheck
options:
  bundleIdPrefix: com.nsantulli
  deploymentTarget:
    iOS: "16.6"
  createIntermediateGroups: true
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    majorVersion: 12.0.0
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "Q2DM9FSRL4"
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: NO
targets:
  EraCheck:
    type: application
    platform: iOS
    sources:
      - path: EraCheck
    dependencies:
      - package: GoogleMobileAds
    resources:
      - path: EraCheck/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nsantulli.eracheck
        INFOPLIST_FILE: EraCheck/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        ENABLE_USER_SCRIPT_SANDBOXING: YES
  EraCheckUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: EraCheckUITests
    dependencies:
      - target: EraCheck
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nsantulli.eracheck.uitests
        GENERATE_INFOPLIST_FILE: YES
        TARGETED_DEVICE_FAMILY: "1"
        TEST_TARGET_NAME: EraCheck
schemes:
  EraCheck:
    build:
      targets:
        EraCheck: all
        EraCheckUITests: [test]
    test:
      targets:
        - EraCheckUITests
